### ISSUE TITLE
Using CMake instructions do not work

### ISSUE THREAD

**Issue by laurent-lao** [sc-odin/docs#1]
At [section](Using CMake (INCOMPLETE)), it seems like the `cmake -DCMAKE_TOOLCHAIN_FILE=cmake/toolchain/bbb.cmake .` does not want to work.

Produces this error

```
CMake Error: The source directory "<shortened>/fprime/build-cross"
does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI.
````

**Comment by Ruben1729** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Using CMake instructions do not work](https://trello.com/c/x913Aeq0/13-using-cmake-instructions-do-not-work)
