### ISSUE TITLE
Missing link for Cloud9/SSH into BBB

### ISSUE THREAD

**Issue by laurent-lao** [sc-odin/docs#2]
In this [section](https://docs-sc-odin.now.sh/#/guide-setting-up-fprime?id=transfer-to-bbb-incomplete, "See here for how to do that" does not have a link.

**Comment by Ruben1729** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Missing link for Cloud9/SSH into BBB](https://trello.com/c/Dj11cdnb/12-missing-link-for-cloud9-ssh-into-bbb)

**Comment by Ruben1729** [comment]
This is no longer a route
