### ISSUE TITLE
Complete Contribution Guide

### ISSUE THREAD

**Issue by laurent-lao** [sc-odin/docs#3]
For [Guide to Contribution](https://github.com/spaceconcordia/sc-odin-docs/blob/master/guide-contribution.md)

- [x] Add contribution instruction
- [x] Add Markdown guide
- [x] Add Website file structure guide

**Comment by laurent-lao** [comment]
@daniela-venuta You can help for this one if you'd like

**Comment by Ruben1729** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Complete contribution guide](https://trello.com/c/zSHV3O8e/11-complete-contribution-guide)

**Comment by Ruben1729** [comment]
This can be closed with the recent [pull request](https://github.com/sc-odin/docs/pull/23)
