### ISSUE TITLE
Link the rest of Fprime's Guides

### ISSUE THREAD

**Issue by laurentlaurent** [sc-odin/docs#8]
Add the rest of Fprime's guides in
`raw-redirect`

- Add the tag that will be used in `index.html`, `remoteMarkdown` array

- Add md file for each fprime guide to be redirected

- Include `[the tag that was added](link to the raw)` in those .md file

- Update `fprime\_sidebar.md` with new files

- [ ] List Fprime guides to be added

**Comment by Ruben1729** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Link the rest of F' Guides](https://trello.com/c/UT6rIz7I/7-link-the-rest-of-f-guides)
