### ISSUE TITLE
Document Fprime build process on macOS

### ISSUE THREAD

**Issue by laurent-lao** [sc-odin/docs#9]
Add the process of building fprime on macOS

Link to this [guide](https://docs.laurentlao.com/#/setting-mac-terminal) as `Get Git, Homebrew and set your PATH`

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by laurent-lao** [comment]
Fixed link https://docs.laurentlao.com/#/mac/setting-mac-terminal

**Comment by laurent-lao** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [F' Installation on Mac Tutorial](https://trello.com/c/hI9IhOOG/5-f-tutorial)

**Comment by Ruben1729** [comment]
This was done https://docs.sc-odin.now.sh/#/fprime-guide/setup-mac
